CREATE TABLE IF NOT EXISTS credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_credito VARCHAR(255) NOT NULL,
    numero_nfse VARCHAR(255) NOT NULL,
    data_constituicao DATE,
    valor_issqn DECIMAL(10,2),
    tipo_credito VARCHAR(255),
    simples_nacional BOOLEAN,
    aliquota DECIMAL(5,2),
    valor_faturado DECIMAL(10,2),
    valor_deducao DECIMAL(10,2),
    base_calculo DECIMAL(10,2)
);
